/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hq.swingmaterialdesign;

import com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author abner
 */
public class MainView extends javax.swing.JFrame {
    int xMouse, yMouse;
    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mPasswordField1 = new com.hq.swingmaterialdesign.materialdesign.MPasswordField();
        mButton1 = new com.hq.swingmaterialdesign.materialdesign.MButton();
        mTextField1 = new com.hq.swingmaterialdesign.materialdesign.MTextField();
        mButton2 = new com.hq.swingmaterialdesign.materialdesign.MButton();
        mComboBox1 = new com.hq.swingmaterialdesign.materialdesign.MComboBox();
        jPanel2 = new javax.swing.JPanel();
        mButton3 = new com.hq.swingmaterialdesign.materialdesign.MButton();
        jLabel1 = new javax.swing.JLabel();
        mGradientButton2 = new com.hq.swingmaterialdesign.materialdesign.MGradientButton();
        mGradientPanel1 = new com.hq.swingmaterialdesign.materialdesign.MGradientPanel();
        jPanel3 = new javax.swing.JPanel();
        mToggleButton1 = new com.hq.swingmaterialdesign.materialdesign.MToggleButton();
        mToggleButton2 = new com.hq.swingmaterialdesign.materialdesign.MToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mPasswordField1.setLabel("Password");
        jPanel1.add(mPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 135, 372, 60));

        mButton1.setBackground(new java.awt.Color(204, 204, 204));
        mButton1.setBorder(null);
        mButton1.setText("A simple button");
        mButton1.setBorderRadius(50);
        mButton1.setFont(new java.awt.Font("Nunito Black", 0, 14)); // NOI18N
        mButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(mButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 220, 50));

        mTextField1.setLabel("Username");
        jPanel1.add(mTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 69, 372, 60));

        mButton2.setBackground(new java.awt.Color(51, 51, 51));
        mButton2.setBorder(null);
        mButton2.setText("Another button");
        mButton2.setBorderRadius(50);
        mButton2.setFont(new java.awt.Font("Nunito Black", 0, 14)); // NOI18N
        mButton2.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.FLAT);
        mButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(mButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 220, 50));

        mComboBox1.setForeground(new java.awt.Color(109, 109, 109));
        mComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select gender", "Male", "Female", "Non binary" }));
        mComboBox1.setAccent(new java.awt.Color(0, 120, 215));
        jPanel1.add(mComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 206, 372, 51));

        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel2MouseReleased(evt);
            }
        });

        mButton3.setText(String.valueOf(MaterialIcons.CLOSE));
        mButton3.setFont(MaterialIcons.ICON_FONT.deriveFont(20f));
        mButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jLabel1.setText("A modern material design form Swing");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(mButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addGap(5, 5, 5))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 599, -1));

        mGradientButton2.setForeground(new java.awt.Color(255, 255, 255));
        mGradientButton2.setText("A gradient button");
        mGradientButton2.setBorderRadius(50);
        mGradientButton2.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        mGradientButton2.setType(com.hq.swingmaterialdesign.materialdesign.MGradientButton.Type.RAISED);
        mGradientButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mGradientButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(mGradientButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 220, 50));

        mGradientPanel1.setBackground(new java.awt.Color(255, 255, 255));
        mGradientPanel1.setBorderRadius(120);
        mGradientPanel1.setFillBackground(false);
        mGradientPanel1.setFillImage(true);

        javax.swing.GroupLayout mGradientPanel1Layout = new javax.swing.GroupLayout(mGradientPanel1);
        mGradientPanel1.setLayout(mGradientPanel1Layout);
        mGradientPanel1Layout.setHorizontalGroup(
            mGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        mGradientPanel1Layout.setVerticalGroup(
            mGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        jPanel1.add(mGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 120, 120));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mToggleButton1.setForeground(new java.awt.Color(255, 255, 255));
        mToggleButton1.setText("Menu option 2");
        mToggleButton1.setBorderRadius(0);
        mToggleButton1.setEndColor(new java.awt.Color(0, 102, 102));
        mToggleButton1.setFont(new java.awt.Font("Nunito SemiBold", 0, 16)); // NOI18N
        mToggleButton1.setHoverEndColor(new java.awt.Color(0, 102, 102));
        mToggleButton1.setHoverStartColor(new java.awt.Color(0, 153, 153));
        mToggleButton1.setIndicatorThickness(4);
        mToggleButton1.setSelectedColor(new java.awt.Color(0, 153, 153));
        mToggleButton1.setStartColor(new java.awt.Color(0, 102, 102));
        mToggleButton1.setType(com.hq.swingmaterialdesign.materialdesign.MToggleButton.Type.FLAT);
        jPanel3.add(mToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 230, 54));

        mToggleButton2.setForeground(new java.awt.Color(255, 255, 255));
        mToggleButton2.setText("menu option 1");
        mToggleButton2.setBorderRadius(0);
        mToggleButton2.setEndColor(new java.awt.Color(0, 102, 102));
        mToggleButton2.setFont(new java.awt.Font("Nunito SemiBold", 0, 16)); // NOI18N
        mToggleButton2.setHoverEndColor(new java.awt.Color(0, 102, 102));
        mToggleButton2.setHoverStartColor(new java.awt.Color(0, 153, 153));
        mToggleButton2.setIndicatorThickness(4);
        mToggleButton2.setSelectedColor(new java.awt.Color(0, 153, 153));
        mToggleButton2.setStartColor(new java.awt.Color(0, 102, 102));
        mToggleButton2.setType(com.hq.swingmaterialdesign.materialdesign.MToggleButton.Type.FLAT);
        jPanel3.add(mToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 230, 54));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_mButton3ActionPerformed

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseReleased
        setOpacity((float) 1.0);
    }//GEN-LAST:event_jPanel2MouseReleased

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        setLocation(evt.getXOnScreen() - xMouse, evt.getYOnScreen() - yMouse);
        setOpacity((float) 0.9);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void mGradientButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mGradientButton2ActionPerformed
        mToggleButton1.unselect();
    }//GEN-LAST:event_mGradientButton2ActionPerformed

    private void mButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mButton1ActionPerformed
        mToggleButton1.unselect();
    }//GEN-LAST:event_mButton1ActionPerformed

    private void mButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mButton2ActionPerformed
        mToggleButton1.unselect();
    }//GEN-LAST:event_mButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private com.hq.swingmaterialdesign.materialdesign.MButton mButton1;
    private com.hq.swingmaterialdesign.materialdesign.MButton mButton2;
    private com.hq.swingmaterialdesign.materialdesign.MButton mButton3;
    private com.hq.swingmaterialdesign.materialdesign.MComboBox mComboBox1;
    private com.hq.swingmaterialdesign.materialdesign.MGradientButton mGradientButton2;
    private com.hq.swingmaterialdesign.materialdesign.MGradientPanel mGradientPanel1;
    private com.hq.swingmaterialdesign.materialdesign.MPasswordField mPasswordField1;
    private com.hq.swingmaterialdesign.materialdesign.MTextField mTextField1;
    private com.hq.swingmaterialdesign.materialdesign.MToggleButton mToggleButton1;
    private com.hq.swingmaterialdesign.materialdesign.MToggleButton mToggleButton2;
    // End of variables declaration//GEN-END:variables
}
